const seed = [
  ['Dbpc_YRKnx9','Coffee shoot / behind the scenes','cinematic'],['DcCq1O5T0M6','arvoの1日 — 朝から夜まで','story'],['Db0TdE9hSep','仕事と暮らしのストーリー','story'],['DZ7RZ-DpZNE','Lunch combo at Dikby','coffee'],['DaTOuM5o48L','Apero? Yes please!','coffee'],['DaNJNSixqGg','Your daily coffee reminder','coffee'],['DZepx4ViQEu','映像で差別化するリール','tutorial'],['DZwgg8Gzmtv','Sound design is easy','sound'],['Db4vgbtt2bA','Cold brew character reel','coffee'],['Db03XWhAdD_','Shoot vs feed','cinematic'],['DZ9GTADTOLt','uneek.bkk coffee shop','coffee'],['DZk9iiONkkO','Food illustration transition','cinematic'],['DWgqzklDIb-','Coffee detail ASMR','sound'],['Da5KLAGNNg4','Why this hook reached 5.2M','tutorial'],['DbLdCqUtD68','3 proven hooks','tutorial'],['DR5cWhakhHu','Cinematic coffee shop','cinematic'],['DXWY4ovj8UV','One slow pour at a time','coffee'],['DMzQ1dmTblZ','Iced latte layers','coffee'],['C6BvxD6r5JF','Sunday coffee with a friend','story'],['CqFgd79IocZ','Coffee commercial BTS','cinematic'],['DZw-1tjps8R','Meet our Mont Blanc','coffee']
].map(([id,title,category],index)=>({id,title,category,url:`https://www.instagram.com/p/${id}/`,index,source:'instagram'}));

const gradients=['linear-gradient(145deg,#5d6a55,#151a15)','linear-gradient(145deg,#725949,#241c17)','linear-gradient(145deg,#535d70,#17191f)','linear-gradient(145deg,#745d35,#251f13)','linear-gradient(145deg,#5e4b5e,#1f171f)'];
function encodeBoard(items){const bytes=new TextEncoder().encode(JSON.stringify(items.map(({id,title,category,url,index,source})=>({id,title,category,url,index,source}))));let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));return btoa(binary).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function decodeBoard(){try{const encoded=new URLSearchParams(location.hash.slice(1)).get('board');if(!encoded)return null;const normalized=encoded.replaceAll('-','+').replaceAll('_','/');const bytes=Uint8Array.from(atob(normalized),c=>c.charCodeAt(0));const parsed=JSON.parse(new TextDecoder().decode(bytes));return Array.isArray(parsed)&&parsed.length?parsed:null}catch{return null}}
const sharedBoard=decodeBoard();
const state={items:sharedBoard||JSON.parse(localStorage.getItem('frame-items')||'null')||seed,filter:'all',query:'',selected:null,localVideo:null,loopIn:null,loopOut:null,looping:false,markers:[],notes:JSON.parse(localStorage.getItem('frame-notes')||'{}')};
const $=s=>document.querySelector(s);const board=$('#board');
const categories=['all','coffee','cinematic','tutorial','sound','story'];
const labels={all:'すべて',coffee:'Coffee',cinematic:'Cinematic',tutorial:'How to',sound:'Sound',story:'Story'};

function save(){localStorage.setItem('frame-items',JSON.stringify(state.items));localStorage.setItem('frame-notes',JSON.stringify(state.notes))}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),1800)}
function renderFilters(){$('#filters').innerHTML=categories.map(x=>`<button class="chip ${state.filter===x?'active':''}" data-filter="${x}">${labels[x]}</button>`).join('')}
function filtered(){let list=state.items.filter(x=>(state.filter==='all'||x.category===state.filter)&&(`${x.title} ${x.category}`.toLowerCase().includes(state.query)));if($('#sortSelect').value==='title')list.sort((a,b)=>a.title.localeCompare(b.title));if($('#sortSelect').value==='notes')list.sort((a,b)=>Number(!!state.notes[b.id])-Number(!!state.notes[a.id]));return list}
function render(){renderFilters();const items=filtered();board.innerHTML=items.map((item,i)=>`<article class="card" data-id="${item.id}" style="--card-bg:${gradients[(item.index??i)%gradients.length]}"><span class="card-fallback"><span>${String(i+1).padStart(2,'0')}</span></span><iframe src="${escapeHtml(item.url)}embed/" title="${escapeHtml(item.title)}" loading="lazy" allowfullscreen allow="encrypted-media; picture-in-picture"></iframe><span class="card-top"><span class="card-number">${String(i+1).padStart(2,'0')} / ${String(items.length).padStart(2,'0')}</span><button class="card-analyze" data-analyze="${item.id}">分析 ↗</button></span><span class="card-copy"><h3>${escapeHtml(item.title)}</h3><span class="card-meta"><span>${state.notes[item.id]?'<i class="note-dot"></i>ANALYZED':labels[item.category]||item.category}</span><span>REEL</span></span></span></article>`).join('');$('#reelCount').textContent=state.items.length;$('#noteCount').textContent=Object.keys(state.notes).length;updateProgress()}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function selectItem(id){state.selected=state.items.find(x=>x.id===id);state.localVideo=null;openPlayer()}
function openPlayer(){const item=state.selected||{id:'local',title:'My footage',url:'#',category:'cinematic'};const isLocal=!!state.localVideo;$('#analysisTitle').textContent=item.title;$('#instagramLink').href=item.url||'#';$('#instagramLink').style.display='none';$('#videoEmpty').style.display='none';$('#video').style.display=isLocal?'block':'none';$('#instagramEmbed').style.display=isLocal?'none':'block';$('#instagramEmbed').src=isLocal?'about:blank':`${item.url}embed/`;$('#precisionNote').style.display=isLocal?'none':'block';$('.viewer-panel').classList.toggle('instagram-mode',!isLocal);const n=state.notes[item.id]||{};$('#whyNote').value=n.why||'';$('#hookNote').value=n.hook||'';$('#pacingNote').value=n.pacing||'Medium';$('#shotNote').value=n.shots||'';$('#audioNote').value=n.audio||'';renderTags(n.tags||[]);const del=$('#deleteReference');del.disabled=!state.items.some(x=>x.id===item.id);del.classList.remove('confirming');del.textContent=del.disabled?'ローカル動画は削除対象外':'このリールを削除';$('#playerDialog').showModal()}
function renderTags(active=[]){$('#tagPicker').innerHTML=['hook','camera','light','edit','sound','color'].map(t=>`<button class="${active.includes(t)?'active':''}" data-tag="${t}">#${t}</button>`).join('')}
function formatTime(s){if(!Number.isFinite(s))s=0;const m=Math.floor(s/60),sec=Math.floor(s%60),ms=Math.floor((s%1)*1000);return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}.${String(ms).padStart(3,'0')}`}
function updateTimeline(){const v=$('#video');$('#currentTime').textContent=formatTime(v.currentTime);$('#duration').textContent=formatTime(v.duration);$('#timeline').value=v.duration?v.currentTime/v.duration*1000:0;$('#playButton').textContent=v.paused?'▶':'Ⅱ';if(state.looping&&state.loopOut!=null&&v.currentTime>=state.loopOut)v.currentTime=state.loopIn||0;renderMarkers()}
function renderMarkers(){const v=$('#video');$('#markerLayer').innerHTML=state.markers.map(m=>`<i class="timeline-marker" style="left:${v.duration?m/v.duration*100:0}%"></i>`).join('')}

$('#filters').addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f){state.filter=f.dataset.filter;render()}});board.addEventListener('click',e=>{const b=e.target.closest('[data-analyze]');if(b)selectItem(b.dataset.analyze)});$('#sortSelect').addEventListener('change',render);$('#searchToggle').onclick=()=>{$('#searchBox').classList.toggle('visible');$('#searchInput').focus()};$('#searchInput').oninput=e=>{state.query=e.target.value.toLowerCase();render()};
$('#shareButton').onclick=async()=>{const shareUrl=`${location.origin}${location.pathname}#board=${encodeBoard(state.items)}`;const data={title:'FRAME — Reel reference board',text:`${state.items.length}本のリール・リファレンス`,url:shareUrl};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(shareUrl);toast('ボードの共有リンクをコピーしました')}}catch{}};
$('#addButton').onclick=()=>$('#addDialog').showModal();$('#addForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const url=$('#newUrl').value;const id=(url.match(/\/(?:p|reel)\/([^/?]+)/)||[])[1]||crypto.randomUUID();state.items.unshift({id,url,title:$('#newTitle').value||'Untitled reference',category:$('#newCategory').value,index:state.items.length,source:'instagram'});save();render();e.target.reset();toast('リファレンスを追加しました')});
$('#uploadButton').onclick=()=>$('#videoInput').click();$('#videoInput').onchange=e=>{const file=e.target.files[0];if(!file)return;if(state.localVideo)URL.revokeObjectURL(state.localVideo);state.localVideo=URL.createObjectURL(file);state.selected={id:`local-${file.name}`,title:file.name,category:'cinematic',source:'local'};const v=$('#video');v.src=state.localVideo;state.markers=[];state.loopIn=state.loopOut=null;openPlayer()};
$('#closePlayer').onclick=()=>{$('#video').pause();$('#playerDialog').close()};$('#playButton').onclick=()=>{$('#video').paused?$('#video').play():$('#video').pause()};$('#backButton').onclick=()=>$('#video').currentTime=Math.max(0,$('#video').currentTime-5);$('#forwardButton').onclick=()=>$('#video').currentTime=Math.min($('#video').duration||0,$('#video').currentTime+5);$('#prevFrame').onclick=()=>$('#video').currentTime=Math.max(0,$('#video').currentTime-1/30);$('#nextFrame').onclick=()=>$('#video').currentTime=Math.min($('#video').duration||0,$('#video').currentTime+1/30);$('#speed').oninput=e=>{$('#video').playbackRate=Number(e.target.value);$('#speedValue').value=`${Number(e.target.value).toFixed(2)}×`};$('#timeline').oninput=e=>{const v=$('#video');if(v.duration)v.currentTime=Number(e.target.value)/1000*v.duration};$('#video').addEventListener('timeupdate',updateTimeline);$('#video').addEventListener('loadedmetadata',updateTimeline);$('#video').addEventListener('play',updateTimeline);$('#video').addEventListener('pause',updateTimeline);$('#setIn').onclick=()=>{state.loopIn=$('#video').currentTime;toast(`IN ${formatTime(state.loopIn)}`)};$('#setOut').onclick=()=>{state.loopOut=$('#video').currentTime;toast(`OUT ${formatTime(state.loopOut)}`)};$('#loopButton').onclick=e=>{state.looping=!state.looping;e.currentTarget.setAttribute('aria-pressed',state.looping);toast(state.looping?'区間ループ ON':'区間ループ OFF')};$('#addMarker').onclick=()=>{state.markers.push($('#video').currentTime);renderMarkers();toast('マーカーを追加しました')};
$('#tagPicker').onclick=e=>{const b=e.target.closest('[data-tag]');if(b)b.classList.toggle('active')};$('#saveAnalysis').onclick=()=>{const id=state.selected?.id||'local';state.notes[id]={why:$('#whyNote').value,hook:$('#hookNote').value,pacing:$('#pacingNote').value,shots:$('#shotNote').value,audio:$('#audioNote').value,tags:[...document.querySelectorAll('#tagPicker .active')].map(x=>x.dataset.tag),markers:state.markers,loop:[state.loopIn,state.loopOut]};save();render();toast('分析を保存しました')};
$('#deleteReference').onclick=e=>{const button=e.currentTarget;const id=state.selected?.id;if(!id||!state.items.some(x=>x.id===id))return;if(!button.classList.contains('confirming')){button.classList.add('confirming');button.textContent='もう一度押して削除';return}state.items=state.items.filter(x=>x.id!==id);delete state.notes[id];save();render();$('#video').pause();$('#playerDialog').close();toast('リールと分析メモを削除しました')};
document.addEventListener('keydown',e=>{if(!$('#playerDialog').open||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();$('#playButton').click()}if(e.key.toLowerCase()==='i')$('#setIn').click();if(e.key.toLowerCase()==='o')$('#setOut').click();if(e.key.toLowerCase()==='m')$('#addMarker').click();if(e.key==='ArrowLeft')$('#prevFrame').click();if(e.key==='ArrowRight')$('#nextFrame').click()});
function updateProgress(){const max=board.scrollWidth-board.clientWidth;const p=max?board.scrollLeft/max:0;$('#scrollProgress').style.width=`${Math.max(12,p*100)}%`}board.addEventListener('scroll',updateProgress,{passive:true});render();
